## CREATE DATABASE store_db CHARACTER SET = UTF8MB4 COLLATE 'utf8mb4_general_ci';

DROP TABLE if EXISTS clients;
CREATE TABLE if NOT EXISTS clients(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	fullname VARCHAR (255) NOT NULL,
	_password VARCHAR (255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	username VARCHAR (255) NOT NULL,
	phone VARCHAR(255) DEFAULT 'N/A',
	address VARCHAR(255) DEFAULT 'N/A',
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT pk_clients PRIMARY KEY(id)
);

DESC clients;

DROP TABLE if EXISTS categories;
CREATE TABLE if NOT EXISTS categories(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	_name VARCHAR(255) NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT pk_categories PRIMARY KEY(id),
	CONSTRAINT uq_categories UNIQUE (_name)
);

DESC categories;

DROP TABLE if EXISTS products;
CREATE TABLE if NOT EXISTS products(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	category_id INT UNSIGNED,
	_code VARCHAR(255) NOT NULL,
	_name VARCHAR(255) NOT NULL,
	image VARCHAR(255) NOT NULL,
	price DECIMAL(7,2) NOT NULL DEFAULT 0.00,
	stock INT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT pk_products PRIMARY KEY(id),
	CONSTRAINT uq_products_name UNIQUE (_name),
	CONSTRAINT uq_products_code UNIQUE (_code)
);
-- ADD RELATIONSHIP PRODUCTS - CATEGORIES
ALTER TABLE products
  ADD CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES
  categories(id) ON UPDATE CASCADE ON DELETE SET NULL 
DESC products;